name: Selenium Tests

on:
  push:
    branches: [main]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome
      options: --shm-size=2g
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Run Selenium tests
      run: mvn verify
      env:
        SELENIUM_HUB_HOST: http://localhost:4444/wd/hub
