name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: 15

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B verify

    - name: Generate Cucumber report
      uses: reportportal/cucumber-report-action@v3.0
      with:
        token: ${{ secrets.REPORTPORTAL_TOKEN }}
        endpoint: ${{ secrets.REPORTPORTAL_ENDPOINT }}
        launch-name: "Testes Automatizados"
        cucumber-json-report: ./target/cucumber-report.json
        attributes: |
          { "Release": "1.0.0" }

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: ./target/cucumber-report

    - name: Run tests
      env:
        BROWSER: chrome
      run: mvn -B test -Dtest=RunCucumberTest

env:
  CHROME_DRIVER_VERSION: 92.0.4515.107
  GECKO_DRIVER_VERSION: v0.30.0
  OPERA_DRIVER_VERSION: v.93
  EDGE_DRIVER_VERSION: 92.0.902.84

services:
  chrome:
    image: selenium/standalone-chrome:${{ env.CHROME_DRIVER_VERSION }}
    ports:
      - 4444:4444

  firefox:
    image: selenium/standalone-firefox:${{ env.GECKO_DRIVER_VERSION }}
    ports:
      - 4445:4444

  opera:
    image: selenium/standalone-opera:${{ env.OPERA_DRIVER_VERSION }}
    ports:
      - 4446:4444

  edge:
    image: selenium/standalone-edge:${{ env.EDGE_DRIVER_VERSION }}
    ports:
      - 4447:4444
