name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
          node-version: '16.x'
          
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Chromedriver
      uses: nanake/install-chromedriver@v1.1.0

    - name: Build with Maven
      run: mvn clean verify

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: target/cucumber-html-reports/
